export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Portfolio} from './Portfolio'
export {default as Contact} from './Contact'
export {default as About} from './About'
export {default as Footer} from './Footer'